### ISSUE TITLE
Confused about how to use it

### ISSUE THREAD

**Issue by realliyifei** [Acidham/forklift-folder#1]
So I search the folder in Alfred as usual : 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/32441766/148146561-67535352-a52e-4f0c-b740-45eb8d8ab6e0.png">

Then how to open it to forklift? I tried all the hotkeys

**Comment by Acidham** [comment]
That's a file/folder action. It depends on what hotkey you defined, but pressing this hotkey enters into file action. 

On my system, it will be TAB key. 

You can configure in Preferences > Universal Actions > Show Actions

**Comment by realliyifei** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/32441766/148330878-9bd05c2f-c6a5-4b0b-be8f-7fa4f71c4cbd.png”>

Thanks I see, so it’s here. It’s very low in the hierarchy list and no shortcut so I need to scroll down each time. Do you have any idea to bump it up a bit?

**Comment by Acidham** [comment]
Just start typing and the list gets smaller ;)

**Comment by realliyifei** [comment]
Holy crap, it works! Thanks!
